Mobile version
10-menachi/capstone pull request #1
Opened 2023-04-25 12:41 UTC by 10-menachi

Added:
- Responsive homepage
- Responsive bout Page
- Event Details
- Program Details
- Featured Guests
- Partners
- Responsive Footer
- Back to top button

2023-04-25 16:40 UTC, ShadyShawkat requested changes
## Hi @10-menachi, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 16:40 UTC, ShadyShawkat commented on html/about.html
> +    </footer>
- [x] Kindly add the "Partners" section at the end of the "About" page on the mobile view to match the given design.
- [x] Please change the background color of the footer section to match the given design.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/234336141-d3c305a6-1951-4574-9b85-38fed264a5df.png) | ![image](https://user-images.githubusercontent.com/62290545/234336405-3a43992d-d5e2-4ecb-86e9-3201c7561ebd.png) |

2023-04-25 16:40 UTC, ShadyShawkat commented on index.html
> +
- [x] Please make sure that the footer section is structured in the same way as the provided template. In other words please remove the footer nav links as they don't exist there in the original design.

![image](https://user-images.githubusercontent.com/62290545/234337416-3f2118eb-45bb-4a69-b204-431625cde859.png)

2023-04-25 16:40 UTC, ShadyShawkat commented on index.html
> +    </section>
- [x] Please edit the styling of this button on the mobile view to match the given design.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/234339053-2770326a-a71e-4209-8b15-0e4bcc86625a.png) | ![image](https://user-images.githubusercontent.com/62290545/234339188-18b3c91d-c928-4a67-8a89-8d7e0403ba02.png) |

2023-04-25 16:40 UTC, ShadyShawkat commented on index.html
> +      </div>
- [x] Please increase the spacing to the left of this section to match the design on the desktop view.
- [x] Please also increase the font size and weight of the header title to match the design.
- [x] Kindly adjust the color of the "date" section below the title to match the given template.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/234340171-6769af09-d92f-4238-83d1-153de604ccb4.png) | ![image](https://user-images.githubusercontent.com/62290545/234340275-9ed53479-d802-4179-9d07-e2222b582ed4.png) |

2023-04-25 16:40 UTC, ShadyShawkat commented on index.html
> +
- Good job populating the "Speakers" section dynamically, however, there are some things that can be improved in the design to better match the design which include:
   - [x] Adding the "Featured Speakers" title to the top of this section.
   - [x] Adjusting the size of the images to match the ones in the design.
   - [x] Adding the black and white checkered background to every image. This can be done using the CSS selectors `before` or `after` and setting them up with a `background-image`. Then you can adjust the positioning of it with the `position` property and adjust its `z-index`.

| Your design | Original design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/234341711-61ebc76e-730d-46e8-8ecc-4f6e63e7efb5.png) | ![image](https://user-images.githubusercontent.com/62290545/234341798-d272b4d8-02c9-4778-a76e-20add98ad31e.png) |

2023-04-26 10:04 UTC, 10-menachi commented on index.html
> +
Noted with thanks :smile:

2023-04-26 10:31 UTC, zieeco commented on html/about.html
> +    </footer>
- Hey :wave: , According to the main design and as pointed out by the previous reviewer, the background of the footer in the mobile version of the About page is white. let's improv on this to match the design as much as we can.

*your design*
![Screenshot from 2023-04-26 11-14-14](https://user-images.githubusercontent.com/59397159/234545905-cafd4f84-2438-46e5-9dad-c7f3e560fac2.png)

2023-04-26 10:31 UTC, zieeco commented on index.html
> +
- [ ] This issue is well-resolved :heavy_check_mark:

2023-04-26 10:31 UTC, zieeco commented on index.html
> +      </div>
- [ ] This issue is well-resolved :heavy_check_mark:

2023-04-26 10:31 UTC, zieeco commented on index.html
> +
- [ ] This issue is well-resolved :heavy_check_mark:

2023-04-26 10:31 UTC, zieeco commented on html/about.html
> +    </footer>
- [ ] This issue is not well-resolved :x:

2023-04-26 10:33 UTC, zieeco requested changes
Hi @10-menachi,


<img height="225" src="https://media4.giphy.com/media/Cm9wKmKMUlRPvdoHgU/giphy-downsized-medium.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Descriptive PR. ✔️
- Good commit messages :+1: 
- linter setup correctly :+1: 

## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 10:56 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @10-menachi 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-04-26 11:00 UTC, merged